### ISSUE TITLE
No create database and when uninstall try to delete /etc

### ISSUE THREAD

**Issue by sabado** [vergoh/vnstat#110]
for the record: compiled into ubuntu 16 srv using install procedure. Result ok, but no way to create database. 

I desisted to use it and uninstalled. uninstall script tried to delete /etc directory. 

 make uninstall
Making uninstall in .
make[1]: Entering directory '/home/xxxx/net/vnstat'
 ( cd '/usr/bin' && rm -f vnstat )
 ( cd '/usr/share/man/man1' && rm -f vnstat.1 vnstatd.1 vnstati.1 )
 ( cd '/usr/share/man/man5' && rm -f vnstat.conf.5 )
 ( cd '/usr/sbin' && rm -f vnstatd )
make  uninstall-hook
make[2]: Entering directory '/home/xxxx/net/vnstat'
rm -f /etc/vnstat.conf
rmdir /etc
rmdir: failed to remove '/etc': Directory not empty
Makefile:2188: recipe for target 'uninstall-hook' failed
make[2]: [uninstall-hook] Error 1 (ignored)

==================================================================
  Note: The database directory has been left untouched.
        It will need to be removed manually if no longer needed.
==================================================================

make[2]: Leaving directory '/home/xxxx/net/vnstat'
make[1]: Leaving directory '/home/xxxx/net/vnstat'

**Comment by vergoh** [comment]
Could you provide more details for the "no way to create database" scenario?
What did you expect, what did you try, what didn't work and what was the end result?

The `rmdir /etc` command being executed during uninstall is something that's expected to happen and normal. Because the configuration allows pointing everything to a different install directory, also the cleanup needs to support removing directories that were possibly created as a result of the install. That is why the `rmdir` command is being used instead of something like `rm -fr` since that will result in the directory being removed only if it's empty after the `vnstat.conf` removal. Obviously, `/etc` will always have other files (if the install isn't done in a container or chroot) so no harm gets done.

**Comment by vergoh** [comment]
Closing due to lack of details.
