### ISSUE TITLE
Make error: ‘O_CLOEXEC’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by carlosgvaso** [vergoh/vnstat#121]
I get an error when trying to compile the software. I used the instructions on INSTALL. Here is the command I ran:

```
$ ./configure --prefix=/usr --sysconfdir=/etc && make
```

Here is the excerpt with the error:

```
depbase=`echo src/fs.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I./src     -g -O2 -I/usr/local/include -MT src/fs.o -MD -MP -MF $depbase.Tpo -c -o src/fs.o src/fs.c &&\
        mv -f $depbase.Tpo $depbase.Po
src/fs.c: In function ‘updatedirownerid’:
src/fs.c:182:37: error: ‘O_CLOEXEC’ undeclared (first use in this function)
src/fs.c:182:37: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [src/fs.o] Error 1
make[1]: Leaving directory `/home/grcroot/vnstat-2.1'
make: *** [all-recursive] Error 1
$
```

**Comment by cantalupo555** [comment]
Have you tried this?
https://humdi.net/wiki/vnstat/install/in_ubuntu

**Comment by carlosgvaso** [comment]
I'm using OpenSUSE, so I tried this instead with the same results: https://humdi.net/wiki/vnstat/install/in_opensuse

I'm stuck on an old version of OpenSUSE: 11.3.

**Comment by vergoh** [comment]
I did some digging and the issue is that O_CLOEXEC is missing from old glibc versions. The oldest distribution I still have active in the test set is Ubuntu 12.04 which apparently is recent enough not to have this issue visible. The last vnStat version which doesn't have that O_CLOEXEC definition is use is 1.17 in case you need something installed right now.

I'll have to investigate if setting up a test environment for this is still feasible as repositories for distributions of that era may no longer be available.

Could you provide the output of `gcc --version` and see which version of glibc / libc is being used?

**Comment by carlosgvaso** [comment]
Thank you, vnStat version 1.17 installs without any issues. Here is the GCC version for OpenSUSE 11.3:

```
$ gcc --version
gcc (SUSE Linux) 4.5.0 20100604 [gcc-4_5-branch revision 160292]
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by vergoh** [comment]
I've managed to get this issue replicated using a Docker container with Ubuntu 10.04. I'll see if I can come up with some sort of fix or workaround for this issue as otherwise there shouldn't be any limitations for supporting these sort of old distribution releases.

Some version information just in case:
```
# gcc --version
gcc (Ubuntu 4.4.3-4ubuntu5.1) 4.4.3
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
# dpkg -l | egrep "GNU C Library|sqlite"
ii  libc-bin                        2.11.1-0ubuntu7.21       Embedded GNU C Library: Binaries
ii  libc-dev-bin                    2.11.1-0ubuntu7.21       Embedded GNU C Library: Development binaries
ii  libc6                           2.11.1-0ubuntu7.21       Embedded GNU C Library: Shared libraries
ii  libc6-dev                       2.11.1-0ubuntu7.21       Embedded GNU C Library: Development Librarie
ii  libsqlite3-0                    3.6.22-1                 SQLite 3 shared library
ii  libsqlite3-dev                  3.6.22-1                 SQLite 3 development files
```

**Comment by carlosgvaso** [comment]
Thanks. Let me know if you want me to test anything on OpenSUSE 11.3.

**Comment by vergoh** [comment]
This is now fixed in the latest development version. There aren't that many other changes compared to version 2.1 so it should be safe to install if you'd want to have a 2.x version running.
