### ISSUE TITLE
vnstati -d --headertext -o *.png have no headertext 

### ISSUE THREAD

**Issue by xuebinshushu** [vergoh/vnstat#123]
# cmd:
 - ` vnstati -d 7 --headertext $(hostname) -o $(hostname).png`
# result: 
![zabbix](https://user-images.githubusercontent.com/25652385/52188462-e4ff6580-286d-11e9-91c3-daaba15ed7e0.png)

**Comment by vergoh** [comment]
`vnstati --version`?

**Comment by vergoh** [comment]
I've checked the version history and, for some reason, the implementation has always been such that the custom header text gets added only to the summary images. I don't recall what the intent was as the man page doesn't list this kind of restriction. Possibly something resulted in a partial implementation getting released and the forgotten. I'll get this fixed in the next release.

**Comment by xuebinshushu** [comment]
> `vnstati --version`？

`version is 2.1`
Please forgive me because the Chinese New Year did not reply to you in time.Thanks.Wish you a Happy New Year.
