### ISSUE TITLE
Configuring data retention

### ISSUE THREAD

**Issue by wimoMisterX** [vergoh/vnstat#124]
Hi,

I couldn't find any documentation in configuring data retention.

Can someone guide me in configuring data retention rules? 

Cheers,

**Comment by vergoh** [comment]
In the configuration file, which installs in Linux by default to /etc/vnstat.conf, you'll find the following block around line 90:
```
# data retention durations (-1 = unlimited, 0 = feature disabled)
5MinuteHours   48
HourlyDays      4
DailyDays      62
MonthlyMonths  25
YearlyYears    -1
TopDayEntries  20
```
The keywords should be obvious enough but the documentation also exists in the vnstat.conf man page (https://github.com/vergoh/vnstat/blob/master/man/vnstat.conf.5 or in html https://humdi.net/vnstat/man/vnstat.conf.html). A restart or reload of the daemon is required if the entries are modified as it will not automatically poll the file for changes.

**Comment by CKranebitter** [comment]
Sorry to resurrect this old question. But how can I access the conf-file from within the docker container? Thanks for your help.

**Comment by vergoh** [comment]
@CKranebitter - if https://github.com/vergoh/vnstat-docker is the docker container you are using then please open a new issue in that project. The issue is likely to be docker specific and as a result other looking for the same solution will then be more likely to find the answer from a more related location than from here.
