### ISSUE TITLE
[v2] are JSON traffic values in the output still in bytes?

### ISSUE THREAD

**Issue by jdillard** [vergoh/vnstat#127]
The documentation says the following, but it seems to have changed to bits between 1.15 and 2.0:

```
--json [mode] [limit]
Show database content for selected interface or all interfaces in json format. All traffic values in the output are in bytes. 
```

**RateUnit** doesn't seem to have an effect on JSON output. Is there a way to control the JSON output now or is the switch to bits a bug? (or the ever possible PEBCAK)

**Comment by vergoh** [comment]
The format of the `--json` output was indeed changed starting from version 2.0 in order to make all the benefits of the new database solution directly available. As a result, the `jsonversion` field found in the output was also update from `1` to `2`. As you did notice, the man page now says

> All traffic values in the output are in bytes.

instead of

> All traffic values in the output are in KiB.

as it was in 1.15 (and in the 1.x version series).

Regarding the **RateUnit** question, the key detail can be found from the `vnstat.conf` man page:

> RateUnit
> Select which unit is used **when traffic rate is visible**. 0 = bytes, 1 = bits.  (vnstat and vnstati only)

The `--json` output doesn't show traffic rate (= something per second) and therefore that selection doesn't have any affect in the output. If you'd need the values in bits for some reason then it's only a matter of multiplying the values by 8.

Note that the difference is however visible for example in the `ratestring` fields if you use `--json` in combination with `-tr` (here `jsonversion` refers to the `-tr` combined output which got included starting from version 1.18 using the same syntax):

```
$ vnstat -tr --json
{"jsonversion":"1","vnstatversion":"2.2 beta2","interface":"em1","sampletime":5,"rx":{"ratestring":"99.00 B/s","bytespersecond":99,"packetspersecond":1,"bytes":495,"packets":6},"tx":{"ratestring":"140.00 B/s","bytespersecond":140,"packetspersecond":1,"bytes":703,"packets":6}}

$ vnstat -tr --json --rateunit
{"jsonversion":"1","vnstatversion":"2.2 beta2","interface":"em1","sampletime":5,"rx":{"ratestring":"889.00 bit/s","bytespersecond":111,"packetspersecond":0,"bytes":556,"packets":4},"tx":{"ratestring":"1.13 kbit/s","bytespersecond":140,"packetspersecond":1,"bytes":704,"packets":7}}
```
I hope this answers your question. As a general rule, use the output that's most suitable for your needs as vnStat has several to choose from. The pre-formatted text and image outputs are usually most suitable when the content isn't parsed in any way. If some scripting is involved then `--online`, `--json` or `--xml` are likely to be the best starting points. Obviously, if I've missed some use case then open a new issue regarding it and I'll see what can be done.

**Comment by jdillard** [comment]
Ah thinks for the detailed information! I think it might be worth adding to the CHANGES file that the JSON schema changed (eg, `days` to `day`, etc) and that the JSON output changed from KiB to bytes.

I had written a Traffic Totals package in pfSense that visualizes the JSON output from vnstat and having those two changes called out would have helped with the update process.

**Comment by vergoh** [comment]
I was expecting (hoping) that the `jsonversion` content would get compared in possible implementations to the value that got used during development and that way some error handling or support for different versions could be done. However, it's now clear that this is something I should have also documented somewhere in more details as at least the man pages (which I try to keep the main source for documentation as the other text files aren't as guaranteed to get installed) don't explain that `jsonversion` is essentially the API version for that specific output. At least the `days` -> `day` etc. changes made the KiB -> bytes change more likely to get noticed.

I'll reopen this so that I don't forget to add necessary extra details to the documentation.
