### ISSUE TITLE
vnstat database is locked

### ISSUE THREAD

**Issue by mylovesaber** [vergoh/vnstat#129]
debian8
vnstat 2.1 by Teemu Toivola <tst at iki dot fi>
```
root@op19o:~# vnstat -d
Error: Failed to get info value for "dbversion" from database (5): database is locked
Error: Unable to open database "/var/lib/vnstat/vnstat.db": Resource temporarily unavailable
```
Then I did the following things:
systemctl restart vnstat
```
root@op19o:~# systemctl status  vnstat
● vnstat.service - vnStat network traffic monitor
   Loaded: loaded (/etc/systemd/system/vnstat.service; enabled)
   Active: active (running) since Tue 2019-04-30 12:56:08 CST; 11min ago
     Docs: man:vnstatd(1)
           man:vnstat(1)
           man:vnstat.conf(5)
 Main PID: 31200 (vnstatd)
   CGroup: /system.slice/vnstat.service
           └─31200 /usr/sbin/vnstatd -n

Apr 30 12:56:08 op19o systemd[1]: Started vnStat network traffic monitor.
root@op19o:~# vnstat -d
Error: Failed to get info value for "dbversion" from database (5): database is locked
Error: Unable to open database "/var/lib/vnstat/vnstat.db": Resource temporarily unavailable
```
I installed vnstat by following this tutorial:
https://github.com/vergoh/vnstat/blob/master/INSTALL.md

**Comment by vergoh** [comment]
This is the first reported case of a "database is locked" issue so this situation isn't likely very common and I'm obviously interested on understanding how to reproduce it in order to avoid such happening in the future.

 * Was this a clean install without any versions of vnStat having been already installed in the system (Debian packaging or source)?
 * Is the shell `history` is still available for those commands executed for the install, could you list those in the order they were executed?
 * `systemctl status vnstat` shows only the latest prints and it's missing all output from the daemon process itself (I'd expect at least `Info: vnStat daemon 2.1 started.` to be visible), does `journalctl -u vnstat` reveal anything else that would have started earlier before the restart?

My guess is that there's somehow an additional daemon process (`vnstatd`) running which is locking the database. If the above questions don't reveal anything obvious then `fuser /var/lib/vnstat/vnstat.db` should provide a list of PIDs accessing the database after which `ps u --pid PID` can be used to identify what those are.

**Comment by mylovesaber** [comment]
I couldn't find those commands you wish to see by using history.I have already typed so many commands.So I reinstalled the server.I will do some test in a few days.
Here is the step during the installation:
```
apt-get install -y libsqlite3-dev
cd ~ && wget https://humdi.net/vnstat/vnstat-latest.tar.gz && tar zxvf vnstat-latest.tar.gz && cd vnstat-*
./configure --prefix=/usr --sysconfdir=/etc && make && make install && vnstatd -d
cp -v examples/systemd/vnstat.service /etc/systemd/system/
systemctl enable vnstat && systemctl start vnstat
vnstat --add -i eth0
nano /etc/vnstat.conf
systemctl restart vnstat
```
BTW,could you change the default value "1000" of MaxBandwidth option to "0" in /etc/vnstat.conf after finishing the installation?This will not cause an exception to the vnstat record due to excessive bandwidth.

**Comment by vergoh** [comment]
Ok, that now explains the issue you are having. You shouldn't be executing `vnstatd -d` after `make install` as the systemd service will take care of doing that. That's most likely how you end up having two daemon processes running and the database appearing to be locked. The `vnstat --add -i eth0` step isn't either needed as the daemon will automatically add all existing interfaces for monitoring when started without any existing database.

Compared to your previous install, if you'd execute those commands now (or after last Sunday to be more exact), you'd be getting version 2.2 instead of version 2.1. This latest version includes improvements which should handle any excessive traffic situations correctly as long as the `MaxBandwidth` value is larger than 0. Setting it to 0 essentially disables several sanity checks and is more likely to cause excessive traffic to be visible.

The minimum Debian 8 specific clean install command documentation for the current release can be found here: https://humdi.net/wiki/vnstat/install/in_debian

**Comment by mylovesaber** [comment]
I followed the guide and the problem appeared again.Here is the step while installing:
```
apt-get install -y libsqlite3-dev
cd ~ && wget https://humdi.net/vnstat/vnstat-latest.tar.gz
tar zxvf vnstat-latest.tar.gz
cd vnstat-*
./configure --prefix=/usr --sysconfdir=/etc && make && make install
cp -v examples/systemd/vnstat.service /etc/systemd/system/
systemctl enable vnstat && systemctl start vnstat
```
Verify that daemon process got started:
`pgrep -c vnstatd`
I can see the reply:1

Another question:How to display the format like:
```
rx: 1MB/s tx: 1MB/s
```

instead of:
```
rx:8Mbits/s tx: 8Mbits/s
```
when executing the command : vnstat -l

Thank you for your reply :-)

**Comment by vergoh** [comment]
Does `systemctl status vnstat` now show that the daemon has really been started? If not then follow the `fuser` command step from my first reply if the database still shows as being locked.

For the `vnstat -l` command you can either add `--rateunit 0` as parameter or set `RateUnit` to `0` in the configuration file.

**Comment by mylovesaber** [comment]
```
root@op19o:~# vnstat -d
Error: Failed to get info value for "dbversion" from database (5): database is locked
Error: Unable to open database "/var/lib/vnstat/vnstat.db": Resource temporarily unavailable

root@op19o:~# systemctl status vnstat -l
● vnstat.service - vnStat network traffic monitor
   Loaded: loaded (/etc/systemd/system/vnstat.service; enabled)
   Active: active (running) since Sun 2019-05-05 20:02:29 CEST; 16h ago
     Docs: man:vnstatd(1)
           man:vnstat(1)
           man:vnstat.conf(5)
 Main PID: 632 (vnstatd)
   CGroup: /system.slice/vnstat.service
           └─632 /usr/sbin/vnstatd -n

May 05 20:02:29 op19o systemd[1]: Started vnStat network traffic monitor.
May 05 20:02:32 op19o vnstatd[632]: Info: vnStat daemon 2.2 started. (pid:632 uid:0 gid:0 64-bit)
May 05 20:02:32 op19o vnstatd[632]: Info: Monitoring (2): eth1 (1000 Mbit) eth0 (1000 Mbit)
May 06 04:35:00 op19o vnstatd[632]: Error: Commit transaction to database failed (5): database is locked

root@op19o:~# journalctl -u vnstat
-- Logs begin at Sun 2019-05-05 20:02:19 CEST, end at Mon 2019-05-06 12:50:20 CEST. --
May 05 20:02:29 op19o systemd[1]: Starting vnStat network traffic monitor...
May 05 20:02:29 op19o systemd[1]: Started vnStat network traffic monitor.
May 05 20:02:32 op19o vnstatd[632]: Info: vnStat daemon 2.2 started. (pid:632 uid:0 gid:0 64-bit)
May 05 20:02:32 op19o vnstatd[632]: Info: Monitoring (2): eth1 (1000 Mbit) eth0 (1000 Mbit)
May 06 04:35:00 op19o vnstatd[632]: Error: Commit transaction to database failed (5): database is lock

root@op19o:~# fuser /var/lib/vnstat/vnstat.db
/var/lib/vnstat/vnstat.db:   632

root@op19o:~# ps u --pid 632
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       632  0.0  0.0  14580  2632 ?        Ds   May05   0:00 /usr/sbin/vnstatd -n
```

**Comment by mylovesaber** [comment]
What's the usage of "vnstat -n"?I didn't see this option in man page.

**Comment by vergoh** [comment]
That's a little bit surprising that the database is still locked even when there appears to be only one process accessing it. I'm also not sure if the log should be understood so everything worked fine for 8 hours until the database somehow became locked. Was that really the case or was there some system clock adjustment also ongoing?

Maybe resetting the database could at least provide an idea if the database somehow gets locked by itself or did it have something to do with the extra daemon process started during the first install.

1. `systemctl stop vnstat`
2. `rm -f /var/lib/vnstat/vnstat.db`
3. `systemctl start vnstat`

The `vnstat` command doesn't have a `-n` parameter but the daemon `vnstatd` has:
```
       -n, --nodaemon
              Stay in foreground attached to the current terminal and start the update process.
```

**Comment by mylovesaber** [comment]
I have sent my server infomation for you. Please check your email.It's just a seedbox with no important file.You can check what happened with vnstat on your own.Anyway,would it be possible not to delete the database?I haven't seen the traffic statistics these days。

**Comment by mylovesaber** [comment]
I found that vnstat -d started working normally when system load dropped.However vnstat didn't count traffic during periods of high load.When system load between12-170,vnstat -d didn't work.Only vnstat -l can work normally.

**Comment by vergoh** [comment]
Thanks for the login details. I was able to do some basic checks until the connection got disconnected and the login didn't appear to anymore be valid after that. Based on what I had time to see, the issue is very likely caused by the extremely high i/o load on the server which then causes delays in every running command. Looking at the process list, most likely exim4 was also having some trouble working. I'm actually surprised that otherwise the system stays up and running with such delays.

There are few debug options available in the daemon which may give details about where the time is being spent and why the database ends up being locked. However, I didn't have time to see the output. Some of the daemon disk access features can be disabled (at least `CheckDiskSpace` comes to mind) and possibly having SQLite in Write-Ahead Logging mode (which would require vnStat source modification as there's no existing toggle for it in version 2.2) could help as it is supposed to use less sync requests by design. In theory, it could be possible that the write delay is causing some sort of unexpected interaction within the daemon main loop and the daemon spends too much time writing the data as a result. By blindly guessing, incrementing `SaveInterval` from 5 minutes to 30 or even 60 minutes could help (or hide the issue). Possibly using a different mount point for the database (or for the data that server was processing) could provide some improvement.

I don't, at least right know, have any good ideas how to replicate that sort of i/o load situation for testing. For example VirtualBox allows throttling cpu time but I don't recall it having the ability to slow disk access. Possibly using some old usb stick are root disk could get close but that would require also getting such system first even installed and running.

`vnstat -l` works because it doesn't do any sort of database access. Only the disk i/o appeared to be really slow while cpu and memory were normally available resulting in the kernel still having the ability to serve traffic queries.

**Comment by mylovesaber** [comment]
Yesterday the staff of oneprovider booted to rescue mode to check my server about ipv6 connection problem.Then they didn't boot to normal mode during the whole night.I have booted to normal mode.This time you can check anything as you need.I seldom reboot the server.The server is used for downloading/uploading torrents sources.It will easily cause the high i/o load problem.So you can easily check and test on my server.You can check more information by typing the address in chrome:
```
ip:8112  #(available only when system loading is under 9)
```
The password is same as login password.You can increase the load by choosing Preferences-ltconfig-use_write_cache and save the setting.This action will easily make the vnstat not working properly if the existing configuration doesn't make vnstat not working.Ltconfig will adjust the libtorrent option value to make dl/ul speed much faster and huge pressure with desk i/o.I hope these operations will give you some help.Thanks for your detailed answer.

**Comment by vergoh** [comment]
I've concluded that tuning any parameters in version 2.2 isn't going to help as long as the disk used for the database is (really) slow to confirm disk writes have completed. With debug prints enabled (and a secondary database directory in use), the worst case scenario that I've seen so far has been the SQLite commit taking 36 minutes to write the data for the last 5 minutes. That in turn then results in some traffic information getting ignored as too long has passed since the previous measurement. The database is locked while SQLite waits for the write operation to complete and that's why queries with `vnstat` fail.

I'm currently evaluating if the changes done in commit 136cfb1fb216b8a1c5e087a25d6c8d11017370dd, which provides an alternative database access mode, help in any way.

**Comment by vergoh** [comment]
The Write-Ahead Logging mode mentioned in my previous comment appears to solve this issue. Based debug prints, in this mode the daemon isn't getting stuck during database writes while still keeping the default 5 minute `SaveInterval` enabled. The write is consistently done in less than half seconds which results in the `vnstat` command having the possibility of getting queries done regardless of system load. A quick comparison (since the load is low right now) shows that version 2.2 is not having visibility for up to 50% of the traffic due to getting stuck during database writes.

**Comment by vergoh** [comment]
The latest git master commit (36acf4b3e7e79bde3ce8cf5ff02051b76e51a1ce) now has all the improvements I can think of for this scenario without reducing the integrity and safety of the database in system error situations. It's also upgrade compatible with version 2.2 without data loss (as usual). There are two settings that need to be changed in order to make the slow disk issue almost go away (my log shows 1-2 "a little bit too slow" warnings daily).

The first configuration change is to set `DatabaseWriteAheadLogging` to `1`. This is what makes the difference and would be the only needed setting if you'd happen to have a more recent libsqlite3 available.

The second configuration change is mainly a workaround for the old libsqlite3. The old version doesn't support reading the database without write permissions if Write-Ahead Logging is used. To bypass this, we can set the daemon to run as the only other user account on that server: `DaemonUser` gets the value `"saber"`. If you some day upgrade to a more recent Debian release then this change isn't going to be needed.
