### ISSUE TITLE
vnstat service not creating database

### ISSUE THREAD

**Issue by bxkx** [vergoh/vnstat#131]
Hi! I was installing vnstat on Debian stable as per instructions, but if I want to start it with systemctl start vnstat I'm getting the following:

> systemd[1]: Started vnStat network traffic monitor.
> vnstatd[23644]: Error: Unable to open database "/var/lib/vnstat/vnstat.db": No such file or directory
> vnstatd[23644]: Exiting...
> systemd[1]: vnstat.service: Main process exited, code=exited, status=1/FAILURE
> systemd[1]: vnstat.service: Unit entered failed state.
> systemd[1]: vnstat.service: Failed with result 'exit-code'.
> systemd[1]: vnstat.service: Service hold-off time over, scheduling restart.
> systemd[1]: Stopped vnStat network traffic monitor.

Could this be because the service tries to start vnstatd -n instead of vnstatd -d?

I've successfully created the database by manually starting the daemon with vnstat -d. I killed the process afterwards and gave the service another try, but I got this:

> vnstatd[19889]: Error: Exec step failed (8: attempt to write a readonly database): "update info set value='2.2' where name='vnstatversion'"
> vnstatd[19889]: Error: Unable to open database "/var/lib/vnstat/vnstat.db": No such file or directory

I even gave the database chmod of 777 and it was owned by root, but to no avail.

I ended up reinstalling it, but without manually starting the daemon this time and decided to open this issue.

**Comment by vergoh** [comment]
1. Is this a clean install or did the system already have an older vnStat version installed from Debian packaging?
2. Which install instructions did you follow, the INSTALL file or something else?

**Comment by bxkx** [comment]
No older version previously installed.
I used the wiki, https://humdi.net/wiki/vnstat/install/in_debian

**Comment by vergoh** [comment]
I managed to get this issue replicated using a clean minimal install of Debian 9.9. The problem appears to be caused by an interaction between the hardening options in the example systemd service file and the version of systemd (232 + possibly some Debian specific changes) that comes with Debian 9.9. The `StateDirectory` option isn't supported yet but `ProtectSystem=strict` causes the filesystem to become read-only from the service point of view which results in the vnStat daemon not having the ability to create or modify its database.

Here are the steps that should fix the issue for you:
 * `systemctl stop vnstat` - just to make sure it doesn't happen to be retrying right now
 * `rm -fr /var/lib/vnstat` - a clean start in case you modified the directory permissions
 * `sed -i -e '/^ProtectSystem=/d' /etc/systemd/system/vnstat.service` - remove the line that's causing issues
 * `systemctl daemon-reload` - because the service file was modified
 * `systemctl start vnstat` - this should now create a new database and start running without issues

I'll also modify the install instruction for Debian in the wiki a little bit so that anyone else following those commands doesn't encounter the same issue. The default example service file will most likely need some tuning for the next release in order to avoid these sort of situations as it would appear those hardening settings aren't always compatible with all systemd versions and I don't have any easy way of testing that for each systemd release.

**Comment by bxkx** [comment]
Thank you for your answer and explanation, it is working now! :)

**Comment by kukudemajia** [comment]
Thank you for your answer and explanation, it is working now! :) +1
