### ISSUE TITLE
Recommended systemd configuration

### ISSUE THREAD

**Issue by seamusdemora** [vergoh/vnstat#132]
I'd like to use `vnStat` on my (headless) Raspberry Pi (RPi). I am running raspbian stretch presently, which is an "offshoot" of Debian. You have two files in your repo at `vnstat/examples/systemd/`. These appear to be the latest examples, and I will assume, that would make them the "best" to use. Can you recommend one of these files over the other for my system? 

In general, fewer disk writes is better as the RPi uses an SD card. 

A similar question I have is this: I learned of `vnstat` recently when I found [this tutorial, apparently published in 2011, yet never updated](https://www.thegeekstuff.com/2011/11/vnstat-network-traffic-monitor/). Is any of this material relevant (or even correct) today?

**Comment by vergoh** [comment]
Systemd is the init system used to start the vnStat daemon. The two alternative example files for systemd are there in order to provide one file which contains most, if not all, of the possible hardening options (which result in requiring a more recent systemd version) and a second example (the `simple` directory) which is pretty much guaranteed to work with any systemd version. Raspbian Stretch has a recent enough systemd version so even the hardened example file will work when installed directly from the repository or once version 2.3 is released. Note that the latest released vnStat version (2.2) currently has only one example service file. The `simple` version was created after issue #131 was raised.

vnStat doesn't have any configuration setting in the systemd service file. Everything there is to configure will end up after install in `/etc/vnstat.conf`. You can either use `man vnstat.conf` to see the longer description for each setting or look at https://humdi.net/vnstat/man/vnstat.conf.html (snapshot from the latest release). If you want to reduce the number or frequency of disk writes then modifying the `SaveInterval` setting is the easiest way to achieve that. The default interval is 5 minutes so setting that to for example 10 minutes would result in half of the disk writes being done. However, even the default setting shouldn't be a problem. I've had one RPi running 24/7 since 2015 with that default 5 minute `SaveInterval` and haven't seen issues with the SD card.

The tutorial you've linked is rather old and would result either in an old version (1.15) or very old version (1.11) getting installed. If you don't have issues following few more steps by installing from a source package then I suggest going with the latest release or the current repository version. The "how to get the package" instructions are in the repository [README.md](https://github.com/vergoh/vnstat/blob/master/README.md) and links also to the relevant [INSTALL.md](https://github.com/vergoh/vnstat/blob/master/INSTALL.md) which documents the install steps. https://humdi.net/wiki/vnstat/install/in_debian may also be of some help as it lists the development packages required for compiling the binaries.

**Comment by seamusdemora** [comment]
Very helpful! Thanks for all of this stuff :)
