### ISSUE TITLE
Cannot to reset to zero

### ISSUE THREAD

**Issue by man2018** [vergoh/vnstat#133]
vnstat -r or vnstat --reset cannot reset to zero, I tried many works, it's stll not reset

**Comment by vergoh** [comment]
1. Which version are you using?
2. What was the result of the commands you executed?
3. What was the expected result?

**Comment by man2018** [comment]
CentOS 7.6(core)

[root@CentOS7 ~]# vnstat -r
[root@CentOS7 ~]# vnstat --reset
[root@CentOS7 ~]# 

[root@CentOS7 ~]# vnstat -r
[root@CentOS7 ~]# vnstat --reset
[root@CentOS7 ~]# vnstat
Database updated: Tue Jun 11 09:44:09 2019

   eth0 since 03/09/19

          rx:  2.47 GiB      tx:  2.45 GiB      total:  4.92 GiB

   monthly
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
       Mar '19         2 KiB |       8 KiB |      10 KiB |    0.00 kbit/s
       Jun '19      2.47 GiB |    2.45 GiB |    4.92 GiB |   47.40 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated      7.35 GiB |    7.29 GiB |   14.64 GiB |

   daily
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     yesterday      2.02 GiB |    2.01 GiB |    4.02 GiB |  390.61 kbit/s
         today    460.86 MiB |  454.76 MiB |  915.62 MiB |  214.01 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated      1.11 GiB |    1.09 GiB |    2.20 GiB |
[root@CentOS7 ~]#

**Comment by vergoh** [comment]
The output of `vnstat --version` is what I was looking for as currently I can only assume you are using something from the 1.x series due to the 2.x versions not having the `--reset` parameter.

The next two questions were for trying to understand what you are trying to achieve. The functionality of `--reset` is documented as following in the 1.x series man page:
```
       -r, --reset
              Reset  the  internal counters in the database for the selected interface. Use this if the interface goes down and back up,
              otherwise that interface will get some extra traffic to its database.  Not needed when the daemon is used.
```
If the real intent is to get all stats back to zero then removing the database and re-creating it is the easiest way to remove all data:

1. stop the daemon if running
2. `vnstat --delete -i eth0`
3. `vnstat --create -i eth0`
4. restart the daemon if it was stopped in step 1

**Comment by man2018** [comment]
Thanks for your help. I have been reset to zero myselft！
