### ISSUE TITLE
Request: modify vnstat.cgi to automatically use hostname and all configured interfaces

### ISSUE THREAD

**Issue by lemmy04** [vergoh/vnstat#142]
Every time I install a fresh build of the openSUSE vnstat rpm I have to manually modify vnstat.cgi to use the hostname of the machine instead of "some server" and to adapt the list of interfaces...
I'm pretty sure perl can be made to do all that without having to edit the cgi every time.

I'd do it myself but I don't know enough perl.

**Comment by vergoh** [comment]
Does the openSUSE rpm deploy the vnstat.cgi file and make it accessible via the httpd?

If that's the case then I'd suggest contacting the maintainer of that rpm and making the same proposal. In the case of the rpm, the used environment is well known as the rpm is (most likely) distribution and version specific.

In the source package I provide, vnstat.cgi is located under the 'examples' directory and doesn't get installed with `make install`. My intent has been for that file to act as a minimum viable example that can be deployed if configured a little bit or used as an example for building something more complex. That's why the content has been kept as simple as possible. That also allows the same content to work regardless of which distribution, be it Linux, BSD or Mac, is used. Getting the list of interfaces would be likely to require far more implementation for getting one file to support all alternatives. For example, vnStat itself has already internally 3 different ways of accessing the list of interfaces. I'm not also sure that everyone wants to expose all interfaces or the real hostname so that would still require some configuration possibilities.

**Comment by vergoh** [comment]
Now version 2.7 contains a parameter for listing the interfaces that are being monitored and I ended up starting to publish a Docker container (https://github.com/vergoh/vnstat-docker / https://hub.docker.com/r/vergoh/vnstat) as installation option, at least the automatic generation of the interface list is something that I'm planning on looking at implementing.
