### ISSUE TITLE
Alias isn't set when add flag is used

### ISSUE THREAD

**Issue by jdillard** [vergoh/vnstat#148]
I am trying to set the alias at the time of adding an interface and while it successfully adds the interface to the DB, it isn't setting the alias:

```
vnstat -i vmx2 --setalias "OPT4" --add
```

Is that expected behavior for the above command?

**Comment by vergoh** [comment]
I assume this from vnStat version 2.4 or at least >= 2.0?

That isn't the behaviour I would have expected just by looking at the command. However, I still had to check how versions <= 1.18 behaved since there doesn't appear to be any mention of that combination in documentation or examples.

The 1.x version series had a different procedure when accessing the database which resulted in it having the possibility of defining the interface alias while creating the database. In versions 2.x, defining the alias is a separate database operation which has a lower priority in the execution order than creating a new entry for a new interface. The new entry creation (`--add`) exits the process regardless of the end result causing the `--setalias` request not to be processed. That's something that shouldn't be too difficult to improve and allow also setting the alias when creating a new entry for a interface.

**Comment by jdillard** [comment]
Correct, it was 2.4 (I should have mentioned that). I think that would make a great enhancement, as it makes programmatically adding interfaces simpler. Thanks!
