### ISSUE TITLE
vnstat misalings columns with month names in german

### ISSUE THREAD

**Issue by mineo** [vergoh/vnstat#15]
Example picture attached. March is called März in german and (I guess) the umlaut leads to some miscalculation. The locale I'm using is `de_DE.UTF-8`.

![bla](https://cloud.githubusercontent.com/assets/78236/6439816/015df94c-c0d7-11e4-8e15-3bc4bfd5afaf.png)

**Comment by vergoh** [comment]
Thanks for this report. The output alignment indeed appears to get messed when an UTF-8 locale is used and a field contains a character that outputs as one but consists of more than one byte. In that situation, the used printf() padding doesn't work correctly since it's counting bytes instead of shown characters.
