### ISSUE TITLE
Timestamp in PNG Generation of vnstat 4 Min inaccurate

### ISSUE THREAD

**Issue by Gill-Bates** [vergoh/vnstat#151]
**Cron:**
`0 * * * * vnstati -h -o /var/www/..../image.png > /dev/null 2>&1`

**Syslog:**
`Jan 30 10:00:01 CRON[25825]: (root) CMD (vnstati -h -o /var/www/..../image.png > /dev/null 2>&1)`

**Timestamp:**
```
stat image.png
Modify: 2020-01-30 10:00:01.380296387 +0100
```

**Result:**

![grafik](https://user-images.githubusercontent.com/25774289/73439051-4c4fd880-434f-11ea-8ca2-13a5c8361115.png)

Tested under Debian Buster with Apache

**Comment by vergoh** [comment]
The timestamp in the image is the date and time of the latest database update for that specific interface. That's why it may not always match the date and time of the image is creation.

Starting from version 2.1, the database writes are synced to full minutes which would allow in your kind of usage scenario the latest data being made visible as long as the cron entry doesn't manage to execute before the database write completes (usually solvable with a sleep of few seconds).
