### ISSUE TITLE
Be able to set SaveInterval in seconds

### ISSUE THREAD

**Issue by basilroztor95** [vergoh/vnstat#157]
Hello! Very cool application, thanks for the support and active development!

It would be nice to let vnstat write data to the database more often than every 1 minute, that is, it would be great to be able to set SaveInterval in seconds.

It would be ideal to update the data every second in my case.

Thanks for attention.

**Comment by vergoh** [comment]
What is the practical scenario for which you'd want to have the database written more often than the current limit of once every minute? What data are you accessing from the data and for what use?

I suspect going below one minute wouldn't be such a good idea since the current default settings result in sqlite really trying to ensure the write has been synced to disk before continuing which in turn can sometimes take far longer than few seconds. That's why you may see warnings in the log when running `vnstatd` in on a system with occasionally slow disk i/o:

```
Mar 19 05:45:07 foo vnstatd[1421]: Warning: Writing cached data to database took 7.1 seconds.
Mar 19 05:50:09 foo vnstatd[1421]: Warning: Writing cached data to database took 8.9 seconds.
Mar 21 05:50:13 foo vnstatd[1421]: Warning: Writing cached data to database took 13.5 seconds.
Mar 22 05:50:13 foo vnstatd[1421]: Warning: Writing cached data to database took 13.0 seconds.
Mar 25 05:50:17 foo vnstatd[1421]: Warning: Writing cached data to database took 17.0 seconds.
```

I that example, I know there's some heavy disk activity being started from cron during those times. Setting `DatabaseWriteAheadLogging` from default `0` to `1` or playing with `DatabaseSynchronous` would also likely help but I prefer to have some slower systems still use the default values just to see that those too work well enough.

**Comment by vergoh** [comment]
Feel free to reopen if you'd want to continue on this topic.
