### ISSUE TITLE
vnStat stuck on future time

### ISSUE THREAD

**Issue by AniLeo** [vergoh/vnstat#160]
A couple weeks ago I manually set PC clock to November 4th to test something, then set it back to automatic datetime with correct date. However, vnstat has been stuck on 2020-11-04 for two weeks (I only noticed now)

```
$ vnstat --hours

 enp8s0  /  hourly

         hour        rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     2020-11-04
         03:00     13,75 MiB |   48,00 MiB |   61,75 MiB |  147,99 kbit/s
     ------------------------+-------------+-------------+---------------
```

```
$ vnstat --days 3

 enp8s0  /  daily

          day        rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     2020-04-03    25,15 GiB |  228,35 GiB |  253,49 GiB |   25,20 Mbit/s
     2020-04-04     5,10 GiB |   12,03 GiB |   17,12 GiB |    1,70 Mbit/s
     2020-11-04    13,75 MiB |   48,00 MiB |   61,75 MiB |   36,22 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated     83,18 MiB |  290,42 MiB |  373,60 MiB |
```

Version: vnStat 2.6
OS: Manjaro 19.0.2 (5.5.16-1-MANJARO)

**Comment by vergoh** [comment]
Does the daemon (`vnstatd`) keep running or does it exit soon after startup with some relevant information about the situation?

I'm guessing Manjaro is likely to be using systemd so `systemctl status vnstat` (or `vnstatd` if that's what the service have been named in Manjaro) may provide the necessary information. `journalctl -u vnstat` should give you a longer log if the log from the status command isn't anymore visible.

**Comment by AniLeo** [comment]
```
abr 18 07:01:54 crystal systemd[1]: vnstat.service: Main process exited, code=exited, status=1/FAILURE
abr 18 07:01:54 crystal systemd[1]: vnstat.service: Failed with result 'exit-code'.
abr 18 07:01:57 crystal systemd[1]: vnstat.service: Scheduled restart job, restart counter is at 2015.
abr 18 07:01:57 crystal systemd[1]: Stopped vnStat network traffic monitor.
abr 18 07:01:57 crystal systemd[1]: Started vnStat network traffic monitor.
abr 18 07:01:57 crystal vnstatd[531158]: Info: vnStat daemon 2.6 started. (pid:531158 uid:0 gid:0 64-bit)
abr 18 07:01:57 crystal vnstatd[531158]: Info: Monitoring (1): enp8s0 (1000 Mbit)
abr 18 07:01:57 crystal vnstatd[531158]: Info: Latest database update is in the future (db: 2020-11-04 03:58:20 > now: 2020-04-18 07:01:57). Giving the system clock up to 5>
abr 18 07:06:57 crystal vnstatd[531158]: Info: Latest database update is still in the future (db: 2020-11-04 03:58:20 > now: 2020-04-18 07:06:57), continuing. Some errors m>
abr 18 07:06:57 crystal vnstatd[531158]: Error: Interface "enp8s0" has previous update date too much in the future, exiting. (1604462300 / 1587190017)
```

**Comment by vergoh** [comment]
The logic in the daemon is currently such that it will accept the previous update date being in the future as long as such difference could be possible due to timezone or daylight saving changes. However, if the difference is greater then it will give the system clock a configured grace period to sync itself up to or past the previous update date. This is needed for those systems without an RTC where the system time may be much in the past in the beginning and having the logic in vnStat reduces the need for hacks previously used in the service files.

Your case is a little bit different than the expected system clock behaviour as you did the date & time setting manually to a future date and then came back to the actual date & time. I didn't plan for such edge case and, as a result, the daemon hasn't any built-in workarounds for this scenario. Possibly it shouldn't either have some automation for this kind of case as I can't think of a good way of detecting if the change was intentional or not.

The good news is that with the new database structure introduced in version 2.0, this can actually be fixed with few commands without discarding old data. You'll need to install the `sqlite3` command for modifying the database if that command instead part of the system already.

The following command resets the previous update date & time back to the current date and time for all interfaces:
```
sudo sqlite3 /var/lib/vnstat/vnstat.db "update interface set updated=datetime('now', 'localtime')"
```

The following commands discard any entries from the database which are more recent than the current date & time:
```
sudo sqlite3 /var/lib/vnstat/vnstat.db "delete from fiveminute where date>datetime('now', 'localtime')"
sudo sqlite3 /var/lib/vnstat/vnstat.db "delete from hour where date>datetime('now', 'localtime')"
sudo sqlite3 /var/lib/vnstat/vnstat.db "delete from day where date>datetime('now', 'localtime')"
sudo sqlite3 /var/lib/vnstat/vnstat.db "delete from month where date>datetime('now', 'localtime')"
sudo sqlite3 /var/lib/vnstat/vnstat.db "delete from top where date>datetime('now', 'localtime')"
```

Be sure to check that the system time is correct before executing these commands. The daemon should restart without issues after those commands have been executed.

I'll add myself a note to come up with some sort of database fixing mode to the daemon itself so that manual `sqlite3` command execution wouldn't be necessary.

**Comment by AniLeo** [comment]
The queries worked, vnStat reporting as normal again

**Comment by imamalfatah** [comment]
Hi, i face same problem now and want to ask is there any way to fix vnstat stuck issue automatically ?
Background problem:
My device is RaspberryPi, there i have Chrony service to tackle date/time drift issue automatically. So in my testing i did set date/time manually +1 day to future and Chrony did the job to sync it back.
But after Chrony finished the sync time back to normal (i have confirm it back to normal), and i leave my device for couple of hour then i just realized that Vnstat continue the network monitoring still in +1 day in future, even though the system date/time has been sync to normal..
So any idea how to tackle this issue automatically ?
Thanks in advance..
