### ISSUE TITLE
Error: Failed to open database "/var/lib/vnstat/vnstat.db" in read-only mode.

### ISSUE THREAD

**Issue by yahia20** [vergoh/vnstat#161]
I am using kali linux as root and I downloaded vmstat by 
using 
$ apt-get install vnstat
when ever I run any command using vnstat I get the same error
example:
$  vnstat 
output:
Error: Failed to open database "/var/lib/vnstat/vnstat.db" in read-only mode.
The vnStat daemon should have created the database when started.
Check that it is configured and running. See also "man vnstatd".

**Comment by vergoh** [comment]
What does `vnstat --version` say?
Did apt configure the daemon (`vnstatd`) and start it?

**Comment by yahia20** [comment]
> What does `vnstat --version` say?

vnStat 2.6 by Teemu Toivola <tst at iki dot fi>

> Did apt configure the daemon (`vnstatd`) and start it?\

I don't know, how do i check

**Comment by cantalupo555** [comment]
`sudo systemctl enable vnstat`
`sudo systemctl start vnstat`

Have you tried this?

**Comment by yahia20** [comment]
> `sudo systemctl enable vnstat`
> `sudo systemctl start vnstat`
> 
> Have you tried this?


thank you it worked
is there an online guide on how to use this tool.

**Comment by cantalupo555** [comment]
> > `sudo systemctl enable vnstat`
> > `sudo systemctl start vnstat`
> > Have you tried this?
> 
> Thank you it worked
> Is there an online guide on how to use this tool?
`man vnstat`

Unfortunately "man vnstat" doesn't have everything, but you can search.
You need to search instructions that use the latest version(2.0+).

Example
https://github.com/vergoh/vnstat/issues/120

**Comment by yahia20** [comment]
> > > `sudo systemctl enable vnstat`
> > > `sudo systemctl start vnstat`
> > > Have you tried this?
> > 
> > 
> > Thank you it worked
> > Is there an online guide on how to use this tool?
> > `man vnstat`
> 
> Unfortunately "man vnstat" doesn't have everything, but you can search.
> You need to search instructions that use the latest version(2.0+).
> 
> Example
> #120

Thank you very much
.

**Comment by vergoh** [comment]
The relevant man pages are available in html format here:
- https://humdi.net/vnstat/man/vnstat.html
- https://humdi.net/vnstat/man/vnstatd.html
- https://humdi.net/vnstat/man/vnstat.conf.html
- https://humdi.net/vnstat/man/vnstati.html (the `vnstati` command may not be part of the `vnstat` package in your distribution)

Those man pages should document all the available parameters of the available commands and the configuration file. However, due to the nature of the man page format, those aren't exactly user guides if you just are looking on the most common usage cases for the tool. In that case, I'd suggest starting with `vnstat --help` and trying the options it lists (that's intentionally the short version of the help). Most of the outputs can then be somewhat customized using the configuration setting in which case reading the vnstat.conf man page (linked above) gives the best overview when read while looking at the content of `/etc/vnstat.conf` (which is the configuration file itself).

**Comment by plutocrat** [comment]
I just had this problem too. I fixed it by editing the systemd service file. The line 
ReadWritePaths=/var/lib/
needed to be changed to 
ReadWritePaths=/var/lib/vnstat
And then the service would start. After running systemctl daemon-reload of course. 
Running on Ubuntu 18.04 LTS.

**Comment by yahia20** [comment]
> I just had this problem too. I fixed it by editing the systemd service file. The line
> ReadWritePaths=/var/lib/
> needed to be changed to
> ReadWritePaths=/var/lib/vnstat
> And then the service would start. After running systemctl daemon-reload of course.
> Running on Ubuntu 18.04 LTS.

thank you but i already fixed the issue

**Comment by vergoh** [comment]
> I've solved it with:
> 
> ```
> cp /var/lib/vnstat/vnstat.db ~/.vnstat/
> ```

This isn't the correct solution as this will result in only access to a database that isn't being updated after the copy operation.
