### ISSUE TITLE
Count 8GB on PPP in 1 second

### ISSUE THREAD

**Issue by Narga** [vergoh/vnstat#18]
Hi,
I got this problem 4 times on this month during connecting via 3G USB (only occur on 3G USB). The counter increase 8Gb suddenly with Download 4GB and Upload 4GB.
I don't know why and facing it few time in this month. How can I find the cause of this problem?

**Comment by vergoh** [comment]
Hi,
which version of vnStat is being used and is the daemon or a cron entry active?

**Comment by Narga** [comment]
I've installet `vnstat v1.13`  on Arch Linux and running it as `systemd` daemon:
```bash
[Unit]
Description=vnStat network traffic monitor
Documentation=man:vnstatd(1) man:vnstat(1) man:vnstat.conf(5)
After=network.target

[Service]
ExecStart=/usr/sbin/vnstatd -n
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target```

**Comment by vergoh** [comment]
Good. The version and the daemon shouldn't then be the reason for the problem. Could you run
`vnstat --showconfig | egrep '^Band|^Max|Interval'`
to show the relevant settings.

**Comment by Narga** [comment]
Here is mine:
```bash
$   vnstat --showconfig | egrep '^Band|^Max|Interval'
BandwidthDetection 1
MaxBandwidth 1000
MaxBWethnone 8
UpdateInterval 30
PollInterval 5
SaveInterval 5
OfflineSaveInterval 30
BandwidthDetectionInterval 5
```

**Comment by vergoh** [comment]
Ok. The problem is essentially the combination of those (default) settings. Usually `BandwidthDetection` would help but it can't be done with PPP interfaces (or at least I don't know how). As a result, vnStat uses the `MaxBandwidth` value as fallback and that value is far to high for a 3G USB interface. Use some speedtest to determinate what the bandwidth of your connection is in a optimum situation and update the `MaxBandwidth` value to match that. You may also want to lower `UpdateInterval` to something like 10. Finally, restart the daemon in order to take new settings into use.

**Comment by Narga** [comment]
Thanks, I've changed it in `/etc/vnstat.conf`, hope it work flawlessly.
One more question. How can I edit the database to fix wrong bandwidth in this month.

**Comment by vergoh** [comment]
Editing the database can be achieved by first exporting the database to a text file using the `--exportdb` parameter, then fixing the wrong information with any plain text editor (note that there are several lines to update, the format is described on the man page) and finally importing the database back using ``--importdb``. The daemon will need to be stopped during this process.

**Comment by Narga** [comment]
It's great, I fixed it but I suggest an example in `man`, `--exportdb` section, I got a little confusion until I found the example in `--importdb` section. :smiley:
