### ISSUE TITLE
----dumpdb removed?

### ISSUE THREAD

**Issue by stk21** [vergoh/vnstat#187]
Thanks for the program.  I had to rebuild a system that had been running for 5+ years that was also leveraging the php web front end. https://github.com/bjd/vnstat-php-frontend/blob/master/vnstat.php

When did the --dumpdb option get removed?  It is possible to add it back as the php web front end has not been updated in a very long time and relied on that output format.

If not can you let me know what the format was of that dump output, and I can see if I can replicate it with the current dump options and see about modifying the current php web front end?

Thanks again for the program.

**Comment by vergoh** [comment]
`--dumpdb` was deprecated in version 1.12 back in 2014 and replaced with `--exportdb`. However, I kept `--dumpdb` still working as it did the same as `--exportdb`. Both were dropped in version 2.0 due to the new database format which has a different internal structure and doesn't need some of the tricks that `--dumpdb` also exposed. vnStat has had `--json` supported since version 1.13 which has been aimed to be used for possible frontends and scripts as it allows limiting the output to only what is intended to be shown instead of everything that's in the database, which can now be a lot since version 2.0 made the data retention time user configurable.

Looking at https://github.com/bjd/vnstat-php-frontend/issues/34, there's a fork https://github.com/thrau/vnstat2-php-frontend which provides directly support for vnStat versions 2.x instead of having to apply some sort of `--json` to `--dumpdb` converter.

**Comment by stk21** [comment]
Thank you for the quick reply sir.  I will checkout the fork.

**Comment by vergoh** [comment]
Using the image output (`vnstati`) is also an alternative. Example: https://humdi.net/vnstat/cgidemo/
