### ISSUE TITLE
Time zone offsets for display and monthly cut-offs

### ISSUE THREAD

**Issue by skandragon** [vergoh/vnstat#189]
My ISP measures time based on Eastern US time -- at midnight on the 21st, a new billing month begins.

However, I live in Central US time, which is 2 hours different.  This isn't usually a major issue, but...

My router is in UTC, which is -7 hours (currently), which can affect daily comparisons greatly.

I'd love to see an option to change the display timezone as well as the cut-off timezone such that it aligns with those two constraints.

I think the display should be easier, but I'm not (yet) sure how the code works, as I've not (yet) looked at it.  :)

**Comment by vergoh** [comment]
The daemon writes to the database using the local timezone and the database structure isn't aware of the used timezone. That results in the daemon not having to worry about timezone changes (like daylight saving time) but obviously has the side effect that re-calculating the data for any specific non-local timezone isn't possible. I suspect that for achieving support for such, the database would need to have the data at a 15 minute resolution (due to some timezones not using full hour offsets) for the entire supported query range, which in turn would cause other side effects. As a result, right now, I don't see any easy solutions to implement in vnStat for this.

You can find the database structure creation from src/dbsql.c in the function db_create() in case you are interested on having a look: https://github.com/vergoh/vnstat/blob/master/src/dbsql.c#L303

**Comment by skandragon** [comment]
Time is hard.  Daylight savings times are stupid.  

I'll have a peek and see what I can work out.  I'm also kind of interested in writing a more detailed flow-based monitor,
since the first question is, "what is my outgoing and incoming bandwidth" and the next question is "who is talking most?"
