### ISSUE TITLE
Per process stats

### ISSUE THREAD

**Issue by kyrias** [vergoh/vnstat#19]
I was wondering if there is any chance that support for per-process stats would be added, because it would be quite useful to have.

**Comment by vergoh** [comment]
Short answer: no

Longer answer:
I'm not aware of any API in the kernel that would provide per process traffic information in the same or similar way that vnStat currently uses for getting the per interface information via the /proc or /sys filesystems. Even if such existed, it would be questionable if extending vnStat with that kind of feature would be the right option instead of having a separate program for doing that. At least the output side would need to be much different in functionality.

**Comment by kyrias** [comment]
Fair enough, had a feeling that you'd want it separate, and it would probably make the code simpler.

**Comment by KAGEYAM4** [comment]
@kyrias  did you found any solutions for per-process stats ?
