### ISSUE TITLE
Database file backup

### ISSUE THREAD

**Issue by giovanni5** [vergoh/vnstat#212]
I have upgraded vnstat and the database now  is vnstat.db. There is a way to convert the old eth0 file to vnstat.db to preserve the historical data?

**Comment by vergoh** [comment]
- From which version to which version did you upgrade?
- How did you perform the upgrade?

All current 2.x versions support automatically importing the data from version 1.x databases (few of the earliest versions excluded) to the new format. In order to avoid issues and inconsistencies, this import is however done only during the first startup and can't be activated manually. If the instructed upgrade procedure was followed then this should have happen automatically. As it apparently didn't, the above questions should provide at least some of the missing details why the import didn't happen.

**Comment by giovanni5** [comment]
Sorry, I should have been more specific. I had vnstat 1.18, then i formatted my drive and intalled the latest version of raspberry os that include vnstat 2.6. There is a way to restore the database to recover the data? I cloned the drive before the upgrade so I have the old eth0 file.

**Comment by vergoh** [comment]
With the following instructions you'll loose any data between the reinstall and now but at least it will give you back the likely longer history:

1. stop the vnStat daemon, most likely `systemctl stop vnstat`
2. verify that it's indeed stopped, `ps aux | grep vnstatd` should show only the grep command
3. check the permissions and owner of the existing vnstat.db and remove it (or move it to some other location as backup, just in case)
4. copy `eth0` (and other possible old files if you had multiple interfaces) to the directory where vnstat.db was and apply the same permissions and owner as vnstat.db had
5. start the vnStat daemon, most likely `systemctl start vnstat`
6. execute `vnstat` and see the historical data restored, `vnstat -y` should also show the yearly data having been reconstructed based on what the old database had

If the new raspberry os for some reason has the interface with a different name then stop the daemon, `vnstat --remove` the newly detected interface, `vnstat --rename` the imported interface to the new name and restart the daemon.

**Comment by giovanni5** [comment]
It works, problem solved, thank you!
