### ISSUE TITLE
importdb option not present

### ISSUE THREAD

**Issue by akash-c** [vergoh/vnstat#227]
Hello,

importdb option not present. I am using v2.6 on Debian. Is there any other way to get the previous data into vnstat?

Any help would be much appreciated.

P.S.: I exported the data using OpenSUSE for which I didn't check the vnstat version.

**Comment by vergoh** [comment]
If you still have the database file(s) instead of the exported text file(s) then you can copy those to /var/lib/vnstat/, stop the currently running vnStat daemon, remove vnstat.db from that directory (this will discard the existing data) and restart the daemon. This will result in a new vnstat.db getting created with all the data imported from the old format database(s).

If you don't have the database file(s) then you'd need to compile version 1.18 locally (no need to install, just having access to the 1.18 `vnstat` command is enough), import the text file(s) to old format database(s) and then proceed with the instructions above.
