### ISSUE TITLE
suggestion: change the name and position of `estimated` row

### ISSUE THREAD

**Issue by Muhammad-2021** [vergoh/vnstat#231]
when i run `vnstat --days -i wlp2s0` it gives:       
```
          day        rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     2022-06-04   905.70 MiB |   19.70 MiB |  925.39 MiB |   89.85 kbit/s
     2022-06-05   854.16 MiB |   42.08 MiB |  896.24 MiB |   87.02 kbit/s
     2022-06-06     1.51 GiB |   27.18 MiB |    1.53 GiB |  152.27 kbit/s
     2022-06-07   404.06 MiB |   27.75 MiB |  431.82 MiB |   41.92 kbit/s
     2022-06-08     1.68 GiB |   55.68 MiB |    1.73 GiB |  172.47 kbit/s
     2022-06-09     1.11 GiB |   29.84 MiB |    1.14 GiB |    3.63 Mbit/s
     ------------------------+-------------+-------------+---------------
     estimated     35.62 GiB |  954.79 MiB |   36.55 GiB |
```
here the estimated row resides under the days data, which seems to be "an estimated sum of the days data", this makes me thought that it's an issue
so please change the name and position

**Comment by vergoh** [comment]
Do you have a better name and position to suggest if the current can apparently be misunderstood?

The current layout has been the same since it's introduction in version 1.1. The `estimated` row can't be right below the last day row without a separator line in between as that reduces the readability. As it is an estimate, `estimated` also directly conveys that information and fits within the limited space of the first column. Note that `estimated` gets replaced with `sum of` when data range queries are used and in such cases the shown information is indeed as sum of the shown data.

**Comment by Muhammad-2021** [comment]
yes, i agree with you on position.
for the name i suggest `predicted`
may be also: `expected`, `evaluated`
other long names: `rate estimator`, `day consumption prediction` .

**Comment by vergoh** [comment]
There's 10 characters currently available for the text/description of the line. I'll see if I can find some other word or way of representing the data since I'll anyway have to touch that area due to #233.
