### ISSUE TITLE
reference to vnstat-server in offical page in vnstat related section

### ISSUE THREAD

**Issue by Hulxv** [vergoh/vnstat#235]
I created a new tool called [vnstat-server](https://github.com/Hulxv/vnstat-server), It's used to serve vnstat data and control it by HTTP requests.
I think it will be useful for those who want to monitor their network traffic from afar or from servers and or use it to make a mobile application to monitor the network traffic on the servers or personal computers or something like that.

So, if there is no problem, can you add it to **vnstat related** section in the [official webpage](https://humdi.net/vnstat/) ?

**Comment by vergoh** [comment]
Link added. I also had a quick look at the content and here's two suggestions:

1) Add https://github.com/marketplace/actions/typos-action to reduce typos in the documentation
2) Split the authentication so that there's a read-only account that gets used most of the time (and may be the only account some of the clients are aware of) and then a separate "admin" account for administrative purposes with permissions for manipulating the configuration and the daemon

**Comment by Hulxv** [comment]
Thank you for adding the link, and thanks for your suggestions.
For sure, I will add typos action, It's really helpful, and about 2nd suggestion. It's really good, I didn't think about it before and It's better from the `read-only` mode in the configuration file.
