### ISSUE TITLE
Is vnstati based on other charting software ? If so, which one ?

### ISSUE THREAD

**Issue by adrianTNT** [vergoh/vnstat#238]
Hello.
The vnstati generated images look very good, I was wondering if it is based on another software or it is custom built inside vnstat. 
I looked in the code a bit to answer that, but I am not good at reading source.

**Comment by vergoh** [comment]
Apart from using the [GD Graphics Library](https://github.com/libgd/libgd) and the built-in fonts it provides, all the outputs of vnStat image output (`vnstati`) have been directly implemented just for it and there's no other framework being used for generating the few different output layouts. Some of the output options have similar style choices as [RRDtool](https://oss.oetiker.ch/rrdtool/) and both use libgd so that may be something that causes a "this looks familiar" feeling to some.
