### ISSUE TITLE
JSON output for -tr (  calculate traffic )

### ISSUE THREAD

**Issue by skechboy** [vergoh/vnstat#25]
Using JSON as output makes vnstat one of the best network monitoring tools. 
However I've noticed that --json parameter is not working in some cases like:
1. live traffic monitoring ( vnstat -l --json )
2. Calculate traffic ( vnstat -tr --json )

Maybe there is some workaround to achieve JSON output in such situations, if not It might turnout to be very handy to add such support.

**Comment by vergoh** [comment]
The JSON output is currently only an alternative format for the database dump (``--exportdb``) with the other alternative being the XML option (``--xml``). That's why it's also practically instant since it only parses the database and no other sources.

Technically, when the daemon is running, it has similar information already available than what the ``-tr`` option provides (but with a delay). The daemon knows the traffic average for the configured ``UpdateInterval`` which is likely to be suitable for most use cases. What's missing is some kind of interprocess communication for the ``vnstat --json`` command to get the traffic information from the daemon. That's something that could be worth investigating.

In what kind of scenario would JSON output for ``vnstat -l`` be usable or needed? The live mode always has a few second delay before it starts producing output and requires the user to exit the process for the output to end.

**Comment by edirpedro** [comment]
Could the JSON output came with Estimated and Average Rates too? Instead of I create another function to calculate this.
