### ISSUE TITLE
Calculate Traffic when vnstat stopped!

### ISSUE THREAD

**Issue by alisalehiman** [vergoh/vnstat#250]
Hello
I wrote a simple script that stop vnstat when it takes a vzdump backup from the vm and starts it after the backup is finished, but unfortunately vnstat is still calculating traffic when it is turned off, and after turning on this value It will be added!
What do I do to temporarily stop calculating a network card?
Vnstat version 2.6 default install with apt on debian 11
Thanks

**Comment by alisalehiman** [comment]
Hi @vergoh 
Would you please check this?

**Comment by vergoh** [comment]
You'd need to add the `--sync` parameter to the daemon startup parameters in order to achieve such behaviour. Because such configuration isn't usually needed, there's no configuration file option available. In Debian 11, you'd need to locate the active `vnstat.service` or `vnstatd.service` file and edit it. By default, it should contain a line like this:
```
ExecStart=/usr/sbin/vnstatd -n
```
Modify it to look like
```
ExecStart=/usr/sbin/vnstatd -n --sync
```
as in, add the `--sync` parameter to the end of whatever that `ExecStart` line has. Finally save the file and reload systemd or reboot. After that change, vnStat will stop trying to track traffic if the daemon is stopped for some time and then restarted without the system being rebooted. The `vnstatd` man page has also some more details regarding this parameter.

**Comment by alisalehiman** [comment]
Hi @vergoh 
Thank you for response.
From which version (--sync) is supported?

**Comment by vergoh** [comment]
It has been there starting from version 1.8: https://github.com/vergoh/vnstat/blob/master/CHANGES#L517
