### ISSUE TITLE
Add granularity beyond an hour to some user defined value down to 1 or 5 minute(s)?

### ISSUE THREAD

**Issue by duffolonious** [vergoh/vnstat#32]
I find myself want 5, or 15 minute intervals as well (coincides with better loadavg for one).

Unfortunately 'm' is already used in the db for month.

**Comment by vergoh** [comment]
Some implementation for this already exists in the slowly progressing sqldb branch (https://github.com/vergoh/vnstat/tree/sqldb). The database structure used in that branch is able to support 5 minute interval for as long as the user wishes to retain the data. As for the current database structure in the master branch, I have no plans on extending it any further.

**Comment by pankajbhanu** [comment]
Is it possible to get hourly reports for more than 24 hours say for the past 1 month. I would like to know the hours of the day during which I get high speed on my connection. In windows I could do this using Networx. It keeps hourly records for the all the time that it has been running. Unfortunately the linux version of Networx doesn't show hourly data. I somehow expected Vnstat to be able to do this since it is much older and is still the preferred utility in linux for bandwidth monitoring. I couldn't find any such option in the mapage of Vnstat. Please point out if I missed something.

**Comment by vergoh** [comment]
The database rewrite is still ongoing in the branch mentioned in my previous comment. It's now close to feature parity with the master branch and will get merged once the last missing features have been completed. It already supports storing at a hourly precision for as long as configured but the included output so far lacks options for accessing older data.
