### ISSUE TITLE
bug for: vnstat -d -s

### ISSUE THREAD

**Issue by maxmitch** [vergoh/vnstat#33]
When I run 

> vnstat -d -s

it returns
```
                      rx      /      tx      /     total    /   estimated
 eth0:
       Dec '15     19.47 MiB  /  543.02 MiB  /  562.49 MiB  /   11.01 GiB
         today     19.47 MiB  /  543.02 MiB  /  562.49 MiB  /    1.01 GiB

```

as you can see, it adds an extra 10 to the days estimate.

**Comment by vergoh** [comment]
Is that output using the current master branch version or something older?
What is the time and date of that specific output?

**Comment by maxmitch** [comment]
> vnstat --version

```
vnStat 1.11 by Teemu Toivola <tst at iki dot fi>
```

I am not sure what you mean by the second question!?

**Comment by vergoh** [comment]
The second question was about the time (hour and minutes of day) and the date when you got the output shown in your first message. Without that information, it becomes harder to verify the estimate calculations. Based on the output, I can only assume that it was the 1st of December, possibly around noon.

The estimate for the line starting with "Dec '15" is for the full month (December) where as the "today" line estimate if only for one day. That's why those estimates aren't identical.

Note that the version you are using is from over 4 years ago. If that is indeed a bug and not a misunderstanding, it may have been already fixed in the current master version.
