### ISSUE TITLE
Ubuntu 15.10 Error

### ISSUE THREAD

**Issue by scriptzteam** [vergoh/vnstat#36]
Just fresh installed and -> Failed to restart vnstat.service: Unit vnstat.service is masked.

 ps aux|grep vnstat
--nothing there ...

**Comment by vergoh** [comment]
How was vnStat installed, from a binary or source package? From where and which version?

**Comment by scriptzteam** [comment]
From github (git clone ....) then ./configure ... make .... make install

anyway i then removed it and installed via apt-get install

#vnstat --help
 vnStat 1.11 by Teemu Toivola <tst at iki dot fi>

and now the database does not updating itself, also it is resetting every day so no history is saved for pas days...

**Comment by vergoh** [comment]
I suspect the first `apt-get remove` may have marked the service file as masked instead of removing it (remove <> purge) in order to avoid even trying to start the service. It may also have left the database directory and possibly database files untouched. You most likely would have needed to execute something like `systemctl unmask vnstat` after the `make install` command to get the service file reactivated, assuming it was indeed left behind.

Did you also remove the database directory before using `apt-get install` again? If that isn't the case then most likely the database directory still existed and was owned by root. If I recall correctly, the apt-get provided package runs the daemon with then `vnstat` user so it wouldn't have access to write database changes to the directory.
