### ISSUE TITLE
Can't build with image output support

### ISSUE THREAD

**Issue by feld** [vergoh/vnstat#38]
I can no longer build with image output support on FreeBSD since you changed to autotools. libgd is installed, we're passing the correct LDFLAGS as always and it simply won't play ball.

Is there a reason you changed to autotools? Your old makefiles worked perfectly fine.

https://www.varnish-cache.org/docs/2.1/phk/autocrap.html

**Comment by feld** [comment]
> checking for gdImageLine in -lgd... no
> 
> configure:  ============================================== 
> configure: 
> configure:        prefix: /usr/local     
> configure:    sysconfdir: ${prefix}/etc 
> configure: 
> configure:    Install paths 
> configure: 
> configure:     vnstat: /usr/local/bin/vnstat 
> configure:    vnstatd: /usr/local/sbin/vnstatd 
> configure:     config: ${prefix}/etc/vnstat.conf 
> configure: 
> configure:    Image output support: disabled 
> configure: 
> configure:  ============================================== 

I assure you, it's there

# strings /usr/local/lib/libgd.so | grep gdImageLine
gdImageLine

**Comment by vergoh** [comment]
I changed to autotools after flags required by the check framework were no longer the same regardless of the version of it being used: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799822

The function for checking libgd availability has at least already been changed to use gdImagePng instead of gdImageLine (#35) but I'm guessing that will not change the end result for you. Most likely you'd need to provide the location of libgd.so with LIBRARY_PATH and CPATH as was sometimes the case even before autotools was being used.

**Comment by ph0s4** [comment]
I had to add

**Comment by ph0s4** [comment]
It works when you add
>CFLAGS+=	-I${LOCALBASE}/include
>LDFLAGS+=	-L${LOCALBASE}/lib
>GNU_CONFIGURE=	yes

to the Makefile, but there were some other issues, too.

Here's a patch to update vnstat in FreeBSD ports:
[vnstat.patch](https://gist.github.com/ph0s4/77cc86a60164e4732a65)
