### ISSUE TITLE
wrong prefix (SI / binary)

### ISSUE THREAD

**Issue by imp1sh** [vergoh/vnstat#41]
When vnstat shows me stats it gives wrong information about the avg. rate.

Example:
```
         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
      01/17/16      1.77 GiB |    1.09 GiB |    2.86 GiB |  277.92 kbit/s
```

That is **wrong** information because 2.86 GiB (Gebibyte) per day equals 284.34 kbit/s.

Either your calculation is wrong or you're just using the wrong prefix. I suspect the latter, because 277.92 kibibyte/s would be right.

I attached a screenshot of my calculations, just to show what I did.
![bildschirmfoto_2016-04-11_14-20-41](https://cloud.githubusercontent.com/assets/3486156/14426628/9640135c-fff0-11e5-8133-d1ce113373c1.png)

**Comment by vergoh** [comment]
I agree, there's an error somewhere in the calculation currently being used in vnStat regarding the traffic rate. The intention was to output as kbit/s but it's now coming out as Kibit/s (the last divisor being 1024 instead of 1000) but with the wrong symbol being used. I'll get this fixed and possibly also add a configuration option for selecting between kbit/s and Kibit/s.

**Comment by imp1sh** [comment]
Sounds great. In my opinion when it comes to transfer rates I'd prefer to get stats based upon the SI prefix, because line speeds are given that way, e.g. Mbit/s.
