### ISSUE TITLE
Static cross compilation with musl fails

### ISSUE THREAD

**Issue by Ypnose** [vergoh/vnstat#53]
Hey,
I'm attempting to statically cross compile <code>vnstat-1.16</code> (same with <code>1.15</code>) to ARM or MIPS64, using <code>musl-1.15</code> but the build fails. The cross-compiler works fine as I was able to compile many other softwares. It is using <code>gcc-6.2.0</code>.
In case you want to look what was done, here the output → https://framagit.org/Ypnose/solyste/snippets/363/raw

**Comment by vergoh** [comment]
Those ``undefined reference to `rpl_malloc'`` and ``undefined reference to `rpl_realloc'`` errors appear to be caused by the ``AC_FUNC_MALLOC`` and ``AC_FUNC_REALLOC`` lines in ``configure.ac``. I'm not even sure if those lines are really needed but I'll need to do some more digging first before removal just to make sure nothing else then breaks. Looking at the autoconf documentation, I suspect there are also few other unnecessary lines currently included.

There's two workarounds that I could find:

Option 1:
1. ``export ac_cv_func_malloc_0_nonnull=yes``
2. ``export ac_cv_func_realloc_0_nonnull=yes``
3. continue with the ``configure`` command as you had done

Option 2:
1. remove ``AC_FUNC_MALLOC`` and ``AC_FUNC_REALLOC`` lines from ``configure.ac``
2. run ``autoreconf -v``
3. continue with the ``configure`` command as you had done

**Comment by Ypnose** [comment]
Hi,
Thank you for your complete answer! Before posting this issue, I saw similar errors on other projects. The "fixes" are very similar to you. I was able to build <code>vnstat</code> using both options you wrote. :+1: 

I also needed to remove <code>install-data-hook</code> block from <code>Makefile.in</code> because the final cross binary cannot be run on the host. I wanted to inform you of this.

**Comment by vergoh** [comment]
Thanks for reporting also the problem in ``install-data-hook``. The next commit should fix these issues.

**Comment by Ypnose** [comment]
I thank you for the very fast hard work! The <code>malloc/realloc</code> changes allows me to cross compile <code>vnstat</code>. Unfortunately, adding autoconf definitions <code>CHOST</code> and <code>CBUILD</code> does not seem to work. The <code>install-data-hook</code> target is still launched. I can tune the Makefile but here the output for debugging purpose: https://framagit.org/Ypnose/solyste/snippets/364/raw

**Comment by vergoh** [comment]
Looks like the documentation I followed regarding ``CHOST`` and ``CBUILD`` wasn't correct and I failed to check if those variables end up having any content. That's why the ``install-data-hook`` changes don't work.

**Comment by Ypnose** [comment]
Kudos for the valuable help. It does the trick!
