### ISSUE TITLE
output in mb

### ISSUE THREAD

**Issue by Michel001** [vergoh/vnstat#54]
i have a question.
i use a shell script to get the output from one month from different servers.
one server has more b/w usage then the other. 
one server gives me 700 mb usage per month
another server gives me 4 gb usage per month.

in my output i get 700 from one server and 4 from the other.
is it possible to get the output in mb ? so i get 700 from one server and 4096 from the other server ?

here is a part of the line i use.
vnstat -m | grep "`date +"%b '%y"`" | awk '{print $3}' > monitor/download.txt

maybe you have another solution that i can get the output in bytes so i can calculate in the script to get back to mb or gb.

**Comment by vergoh** [comment]
That's a good question and I now realize that there's no obvious way of getting that sort of output without having the automatically adjusting unit already included. Originally, ``--oneline`` was implemented for scripting purposes but it lacks the possibility of getting all output in bytes instead of some automatic unit. It's nice for anything that displays the values directly but clumsy if some comparisons or calculations need to be done. That's something I'll have to fix in the next version.

There's however plenty of other output options to play with that are somewhat easy to parse depending on the used script or programming language. Usually, one of ``--json``, ``--xml`` or ``--exportdb`` provides the necessary information without too much parsing. At least with Python, importing the ``--json`` output makes the task trivial but the same output isn't that nice to parse with a shell script.

Here's what I came up with for bash etc. that will continue to work even with version 2.0:
``vnstat --xml m | egrep "month id.*$(date +"<year>%Y</year><month>%m</month>")" | cut -d\> -f9 | cut -d\< -f1``

That will give you the monthly received data in kilobytes in vnStat versions 1.x (those that support ``--xml``) and in bytes in version 2.x (none released yet).

A simpler version for versionx 1.x for getting "latest month":
``vnstat --xml m | grep 'month id=' | head -n 1 | cut -d\> -f9 | cut -d\< -f1``

Same for 2.x (the dump order is different):
``vnstat --xml m | grep 'month id=' | tail -n 1 | cut -d\> -f9 | cut -d\< -f1``

**Comment by Michel001** [comment]
Thanks for the reply.

I have 1.11 running. but it seems that i get no output. 
i will try to update to 1.16 and see if it makes a difference.

**Comment by Michel001** [comment]
i have tried to update. (ubuntu 14.04)
did wget for 1.16
make didn't work.
i had to sudo apt-get build-dep vnstat
./configure
make install
it ran but still vnstat -v shows 1.11
output remains the same.

**Comment by vergoh** [comment]
Using ``./configure`` without any parameters will cause the binaries to be installed to directories that aren't within the PATH by default. If you still have the source directory available where you executed those commands then start with ``make uninstall`` to remove those binaries that ended up in wrong locations. The execute ``./configure --prefix=/usr --sysconfdir=/etc && make`` as instructed right at the beginning of the INSTALL file followed by ``make install``. That should get the binary locations right.

The extra parameter support for ``--xml`` was added in version 1.14 which would explain why the command didn't work with 1.11.

**Comment by Michel001** [comment]
Thank you !!

i am getting the output now.
