### ISSUE TITLE
statistics is not correct

### ISSUE THREAD

**Issue by Buffer2Disk** [vergoh/vnstat#62]
hello，i use vnstat to monitor my server , but something that confuse me .

and this happen in 2017.06.24  12:00 am , ,so much traffic appear in an hour , but traffic appear normal on my server provider.

![qq 20170625123003](https://user-images.githubusercontent.com/4065940/27513680-707eed16-59a2-11e7-9e74-5cb38410d1bc.png)

server infomation :
centos 6.8

**Comment by vergoh** [comment]
Which version of vnStat is being used? I suspect the ``MaxBandwidth`` setting in ``/etc/vnstat.conf`` is incorrect or the feature has been disabled. That would remove the sanity checks that avoid having that sort of traffic reported. The use of a cron entry instead of the daemon can also result in this kind of behaviour.

**Comment by Buffer2Disk** [comment]
vnStat 1.11 by Teemu Toivola ，i just use vnstat as its default.

**Comment by iamatacos** [comment]
maybe it is time to update vnstat ...

**Comment by vergoh** [comment]
Not all distribution provided binary packages of vnStat use the default configuration settings in the way I've set those and that may result in different behaviour in problem situations than intended. It's also worth noting that version 1.11 is over 6 years old so it lacks fixes and sanity checks added since then.

**Comment by hub2git** [comment]
@Buffer2Disk, why not upgrade to version 1.17 and see if that fixes your issue.
