### ISSUE TITLE
vnstat complains about tun0 speed of 10Mbit

### ISSUE THREAD

**Issue by bassmadrigal** [vergoh/vnstat#81]
My /var/log/messages file is getting slammed with vnstatd output every 30 seconds complaining: `Traffic rate for "tun0" higher than set maximum 10 Mbit (30->42, r282 t7), syncing.` There is almost 3000 entries in there in under 3 days.

As best as I can tell in my searching, tun0's speed is set by the kernel and obviously doesn't reflect the actual connection speed. Is there a way for vnstat to ignore this without turning off bandwidth detection?

I have both eth0 and tun0 active, and only a handful of programs are using tun0, while the rest use just eth0. I am running this on Slackware 14.2 using [this SlackBuild](https://slackbuilds.org/repository/14.2/network/vnstat/) (a SlackBuild is a shell script to compile software and package it). If you have any questions or need more information, don't hesitate to ask.

**Comment by vergoh** [comment]
You can define the correct setting for tun0 in the configuration file ``/etc/vnstat.conf`` by adding a line like ``MaxBWtun0 1000`` where 1000 has been updated with the correct bandwidth setting for the interface. Once the configuration file has been changed, restart the daemon in order to get the new settings into effect. This should solve the warning you get in the log.

**Comment by bassmadrigal** [comment]
Beautiful! I guess I should've dug through the conf file since it was documented in there. I'm going to close this. Hopefully others who search for it can now come across this and find the answer rather than opening a new issue.

Thanks for the great program!
