### ISSUE TITLE
Daemonising shoots database file descriptors

### ISSUE THREAD

**Issue by hmw42** [vergoh/vnstat#82]
I tried the sqldb branch and it seems to work as long as vnstatd isn't daemonised. If it is daemonised, it runs but doesn't write any data to the database. The reason is in daemonize() (daemon.c): all file descriptors -including those that are associated with the sqlite database, excl. pidfile- are closed there.

Does vnstatd really needs to close all file descriptors? I mean we are in the state of starting up, we should know all the file descriptors, we want to close. 0, 1 and 2 maybe.

**Comment by vergoh** [comment]
Thanks for taking the time to try the sqldb branch. Your finding is indeed correct. ``vnstatd`` doesn't currently work correctly if started as a daemon because the database connection gets closed when daemonize() is called. It's something I've managed to miss while testing due to having so far kept all the debug prints visible while comparing that the measurements match those done at the same time with a 1.x release vnstatd (and they do).

I recall several daemonization guides suggest closing all open file descriptors apart from those that are known to be used by the daemon itself instead of closing only some specific file descriptors. The problem here is mainly that the database is missing from that list of what is expected to be kept open. The current implementation also lacks the ability of noticing the connection is no longer open (possibly with sqlite3_db_status()) and then trying to reopen it if needed. Both will need to be implemented before release.

**Comment by hmw42** [comment]
As a work around I've patched daemon.c as follows:

`
diff --git a/src/daemon.c b/src/daemon.c
index 45765f1..37f4fa5 100644
--- a/src/daemon.c
+++ b/src/daemon.c
@@ -53,12 +53,18 @@ void daemonize(void)
        }
 
        /* close all descriptors except lock file */
+#if 0
        for (i=getdtablesize();i>=0;--i) {
                if (i!=pidfile) {
                        close(i);
                }
        }
-
+#else
+        close(0);
+        close(1);
+        close(2);
+#endif
+        
        /* redirect standard i/o to null */
        i=open("/dev/null",O_RDWR); /* stdin */
`

That results in five open fds after daemonising; 0, 1, 2, the pid file and the database.

I won't promise anything (as for all of you, time is a scarce resource for me), but maybe I look into that and the error handling of the database access in the... next months.

Thank you for your work!

**Comment by vergoh** [comment]
The sqlite documentation says (https://www.sqlite.org/faq.html#q6):
> Under Unix, you should not carry an open SQLite database across a fork() system call into the child process.

I also concluded that using sqlite3_db_status() wouldn't have the end result I was looking for and ended up improving how the actual sqlite function call return codes are handled. That's now included in commit 477d32d7e0d82ddd7e6aa8b12941418de785004c.
