### ISSUE TITLE
Config file, data retension durations

### ISSUE THREAD

**Issue by hmw42** [vergoh/vnstat#84]
Hello,
 
what is the difference between an unlimited and a disabled data retension duration?

I set configuration options HourlyDays and friends to -1 in order to collect unlimited data samples. When parsing that configuration option setcfgvalue() (from cfg.c) does nothing and returns 0. That is because this option's value doesn't have a namelen associated and it doesn't start with a digit. As a result the default option value is used and that is far away from being unlimited ;).

validatecfg() seems to  be the only place where -1 is to be considered a valid value for configuration options like HourlyDays. In dbsql.c, data is cleaned up only if the option's value is >0. If there is no difference (meant) between unlimited and disabled, maybe removing this comment from the example vnstat.conf file might help avoiding confusion?

Regards
hmw

**Comment by vergoh** [comment]
Looks like another bug, mainly gone unnoticed due to a missing testcase and setcfgvalue() doesn't support negative numbers as a result causing any negative setting in the configuration to revert back to the default value. ``vnstat -D --config cfg/vnstat.conf --showconfig`` did actually also show this for ``YearlyYears`` but it wasn't obvious enough since it defaults to -1 anyway.

The intent for "unlimited / -1" is to allow data collection for the specific feature as long as there's diskspace available. The data should never get cleaned if this setting has been set. On the other hand, if "disabled / 0" is selected then no data for the specific feature gets stored in the database. The check may not be that evident in https://github.com/vergoh/vnstat/blob/sqldb/src/dbsql.c#L609 and could possibly use a comment to clarify it's there.
