### ISSUE TITLE
Convert stats to non-ISO units

### ISSUE THREAD

**Issue by graham8** [vergoh/vnstat#86]
It would be good to get stats in units of GB/MB since many (all?) ISPs use these units when charging.  Having these units just as a display option is confusing.

Edit: or is this fixed in 1.16? (only 1.15 in my repo)

**Comment by vergoh** [comment]
It really depends what those GB/MB your ISP reports are in reality: https://en.wikipedia.org/wiki/Megabyte

You can pick both metric and JEDEC representations and end up with different numbers with the same unit and then increase the confusion by dropping the "i" for the IEC units.

The 1.x versions of vnStat support only binary units, mostly due to too many levels of hardcoding. A majority of those have been refactored out on the 2.x branch so that should allow better configurability in the future. I'm however not sure, at least right know, what that configurability should look like so that any confusion could be avoided.

**Comment by graham8** [comment]
Well my ISP definately sells GB, not GiB and I suspect most do, just like hard disk manufacturers so you think you are getting more for your money!

But for vnstat, if it says GiB it should be GiB, if it says GB it should be GB IMVHO. No confusion for your typical user of vnstat I would say.

Thanks for a great little app.

**Comment by vergoh** [comment]
I did some searching regarding how other programs in Linux handle the units and often this bug report gets referred: https://bugs.launchpad.net/ubuntu/+source/net-tools/+bug/240073

Even now, the situation for ``ifconfig`` isn't as clear as I would have hoped. In Ubuntu, it appears to be using B/KB/MB/GB... (note the uppercase K instead of the expected lowercase k) where the units are actually 1000^n. In Debian (or at least raspbian), the ouput uses B/KiB/MiB/GiB... with 1024^n.

The current unit configuration options for vnStat are:

1. ``UnitMode`` - which selects between the discussed MB/GB <> MiB/GiB while always keeping the 1024^n base
2. ``RateUnit`` - for selecting between bytes and bits, this only applies when traffic rate is shown
3. ``RateUnitMode`` - matter only if ``RateUnit`` has been set to bits in which case the selection is between Kibit/s and kbit/s, here the selection actually changes the base between 1024^n and 1000^n (although I suspect there may be some slight errors in 1.x versions)

We probably both can agree that the JEDEC representation should be dropped out to reduce any extra confusion. However, I'm also thinking that, assuming the current three settings are clear enough from configurability point of view, ``UnitMode`` would need to be renamed to something else in order to force users to check their settings and the description of the new setting. Possibly something like ``DataUnit`` could be the name for the replacement.

Comments are welcome before I start implementing anything.

**Comment by graham8** [comment]
I think you should not look to other software for a role model and the different handling of rate units and other units needs to be corrected.

If proper unit conversion is implemented and the setting re-named, DataUnitMode would work better by analogy with RateUnitMode.

**Comment by tlsalex** [comment]
man page from centos -- ifconfig Using IEC 60027-2 units. So 1 KiB are 2^10 byte.
Maybe should follow the same rule.

![image](https://user-images.githubusercontent.com/36788337/73232105-20045280-41bd-11ea-8bed-ceb499b848b1.png)

**Comment by vergoh** [comment]
As shown above, the commit 09fb52f that was used to close this issue introduced more options for which units are used. The default is still the IEC units. 2^10 is 1024 which is the same the documentation refers to so I don't see anything that needs changing.
