### ISSUE TITLE
Please supply a signature file for releases

### ISSUE THREAD

**Issue by cgzones** [vergoh/vnstat#90]
Please supply a signature file for the vnstat releases, as this reduces the change of foreign code modification.
See https://lintian.debian.org/tags/debian-watch-does-not-check-gpg-signature.html for reasoning and https://github.com/logrotate/logrotate/#download and for an example.

**Comment by vergoh** [comment]
Thanks for the suggestion and links. This has now been handled and all past releases have signature files available in https://humdi.net/vnstat/ which finally has a non-self-signed ssl certificate in use since last weekend (not enforced from http to https yet).

It looks like I'll have to change my release procedure a little bit as there doesn't appear to be a way of including release notes and files for github from the git command line when tagging releases. Adding release notes and file to the 1.17 release resulted in github showing it as a new releases even when the 1.17 tag already existed so I'm not going to update any older releases with change notes + files.

1.18 may get released during this weekend unless I stumble into some issue that I still want to get fixed. After that, the plan is the merge the 2.0 branch (sqlite) to master and start finalizing it for release.
