### ISSUE TITLE
Android Network Monitoring Issue

### ISSUE THREAD

**Issue by icmpnorequest** [vergoh/vnstat#97]
Can I apply this monitoring function in Andorid?
Please give me some tips.

**Comment by vergoh** [comment]
Depends what you are looking for. If you'd want to see vnStat as an Android app then that's something I don't currently have any intention of doing, especially since the apps are, if I remember correctly, written in Java and vnStat on the other hand in C.

In theory, some sort of support might be possible as Android uses a Linux kernel but I have no idea about the userland or how to access it, it's not something that's normally available in Android phones at least. Other embedded devices often are arm based and have a close to standard Linux running and those are already supported by vnStat.

**Comment by ak2766** [comment]
I'd like to see something like this too on Android.  Maybe a kickstarter to see if there's more interest other than just the 2 of us requesting it here.

**Comment by vergoh** [comment]
Is there some specific set of features you are looking for that the already existing Android apps don't offer? At least based on a quick search, there are several apps available which provide similar features for Android than what vnStat does on Linux/BSD.
