### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by borekon** [vergoh/vnstat#98]
In a Debian 9 x64 system i'm unable to make it run.
`systemctl status vnstat` shows:
` vnstat.service: Main process exited, code=exited, status=1/FAILURE`  
`vnstat.service: Unit entered failed state.  `
`vnstat.service: Failed with result 'exit-code'.  `
`vnstat.service: Service hold-off time over, scheduling restart.  `
`Stopped vnStat network traffic monitor.  `
`vnstat.service: Start request repeated too quickly.  `
`Failed to start vnStat network traffic monitor.  `
`vnstat.service: Unit entered failed state.  `
`vnstat.service: Failed with result 'exit-code'.`
Followed all steps in README. Executing `vnstat -d` also shows an error:  
`Error: Unable to open database directory "/var/lib/vnstat": non-existen file or directory`  
`The vnStat daemon should have created this directory when started.`

**Comment by borekon** [comment]
I've tried it in a orange pi with raspbian and is working fine

**Comment by vergoh** [comment]
Which version of vnStat are you using and how was it installed?

**Comment by borekon** [comment]
Downloaded and extracted using `wget https://humdi.net/vnstat/vnstat-latest.tar.gz` and `tar zxvf vnstat-latest.tar.gz` as seen on README.md.  
Then installed with `./configure --prefix=/usr --sysconfdir=/etc && make` and `sudo make install`  
Copied the `systemd` service with sudo as well.

**Comment by vergoh** [comment]
What does `sudo vnstatd -D -n` output?
For some reason, the real error message is missing from the systemd status, possibly hidden by more recent message.

**Comment by vergoh** [comment]
That output is from the `vnstat` command and not the `vnstatd` command. Note the extra "d" for the daemon process.

**Comment by borekon** [comment]
Sorry for the mistake.
[Here you go](http://pasted.co/d62fee28)

**Comment by vergoh** [comment]
Once more as this time the `-n` parameter is missing resulting in the daemon not trying to start making any errors not visible.

**Comment by borekon** [comment]
Oh God, what a shame.
Here you go 
http://pasted.co/ca3bb1c1

**Comment by borekon** [comment]
After running `sudo vnstatd -D -n` now the service is running wit no problems.
I don't know what happened, but usind `sudo make install` all the files and permissions are supposed to be set correctly. Moreover, the system service is running as root, why the error?

**Comment by vergoh** [comment]
I'm don't know what did happen as the error isn't visible in any of the outputs you've shown. The install procedure itself has been tested multiple times in all kinds of systems by copypasting directly from the instructions and I haven't seen this sort of scenario happen any time. The closest I can think of was a manual upgrade in FreeBSD over an already installed version from ports to 2.0 and that mainly failed at first due to the service file that had previously been installed. Did you system have the Debian provided package previously installed at some point before installing the source package?

Since you have systemd in use, it could still be possible getting some more clues from its log. I suspect the service status doesn't show enough lines resulting in the error message from the daemon not being visible. `journalctl -u vnstat` should show everything starting from the beginning.

**Comment by borekon** [comment]
The file is quita large.
Anyway [there you go the pastbin file](http://pasted.co/6e4211da)
I'll try to reproduce all the installation steps and provide all the outputs to you

**Comment by borekon** [comment]
Uninstalled and installed from scratch and now it's working like a charm.
I may forgot the  `vnstatd -d` parameter as sudo or misstyped the `d` letter.
Anyway thank you for your time.
